language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=flake8,py27-django18,py27-django19,py27-django110,py27-django111,coverage
    - python: "3.3"
      env: TOXENV=py33-django18
    - python: "3.4"
      env: TOXENV=py34-django18,py34-django19,py34-django110,py34-django111,py34-django20
    - python: "3.5"
      env: TOXENV=py35-django18,py35-django19,py35-django110,py35-django111,py35-django20,py35-django21
    - python: "3.6"
      env: TOXENV=py36-django111,py36-django20,py36-django21
    - python: "3.7"
      env: TOXENV=py37-django111,py37-django20,py37-django21
install:
  - pip install 'tox>=2.9,<3' 'virtualenv<14.0.0'
script:
  - tox
