language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.4.19
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.6
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.19
    - python: "3.3"
      env: DJANGO_VERSION=1.4.19
    - python: "3.4"
      env: DJANGO_VERSION=1.4.19
    - python: "2.6"
      env: DJANGO_VERSION=1.7.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -e . -r requirements-test.txt
  - pip install coveralls
before_script:
  - make lint
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests/test_project
  - export DJANGO_SETTINGS_MODULE=project.settings
  - make coverage
after_success:
  - coveralls
