language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.8
  - DJANGO_VERSION=2.0.1
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.9.13
    - python: "3.3"
      env: DJANGO_VERSION=1.9.13
    - python: "3.2"
      env: DJANGO_VERSION=1.10.8
    - python: "3.3"
      env: DJANGO_VERSION=1.10.8
    - python: "3.3"
      env: DJANGO_VERSION=1.11.8
    - python: "3.2"
      env: DJANGO_VERSION=1.11.8
    - python: "3.3"
      env: DJANGO_VERSION=2.0.1
    - python: "3.2"
      env: DJANGO_VERSION=2.0.1
before_install:
  # Downgrade virtualenv version due to Python 3.2 drop support
  # in virtualenv >= 14.0.0
  - pip install --upgrade virtualenv==13.1.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements-test.txt
  - pip install -q -e .
  - pip install coveralls
before_script:
  - make lint
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests/test_project
  - export DJANGO_SETTINGS_MODULE=project.settings
  - make test
after_success:
  - make coverage
  - coveralls
