language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.9
    - python: "3.3"
      env: DJANGO_VERSION=1.9
    - python: "3.2"
      env: DJANGO_VERSION=1.10
    - python: "3.3"
      env: DJANGO_VERSION=1.10
    - python: "3.3"
      env: DJANGO_VERSION=1.11
    - python: "3.2"
      env: DJANGO_VERSION=1.11
before_install:
  - sudo apt-get install -y shtool
  - shtool version -s "${DJANGO_VERSION}.0" dj_version.txt
  - shtool version -i r dj_version.txt
  # Required to support Python 3.2, should be able to be removed
  # when support for Django 1.8 / Python 3.2 is dropped.
  - pip install "pip<8" "setuptools<30" "virtualenv<14"
install:
  - NEW_DJANGO_VERSION=$(shtool version -d short dj_version.txt)
  - pip install -q "Django>=${DJANGO_VERSION},<${NEW_DJANGO_VERSION}"
  - pip install -q -e . -r requirements-test.txt
  - pip install coveralls
before_script:
  - make lint
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests/test_project
  - export DJANGO_SETTINGS_MODULE=project.settings
  - make coverage
after_success:
  - coveralls
