dist: xenial
language: python
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35-django22
    - python: "3.6"
      env: TOXENV=py36-django22,py36-django30,py36-django31
    - python: "3.7"
      env: TOXENV=flake8,py37-django22,py37-django30,py37-django31,coverage
#    - python: "3.8"
#      env: TOXENV=py38-django22,py38-django30,py38-django31
install:
  - pip install -r requirements-tools.txt
script:
  - tox
after_success:
  - coveralls
